import { Block, Color, CrystalStructure, DecayMode, ElectricalType, GasAtomicMultiplicities, MagneticType, Phase, Series, type PTDCElementRefined } from "./elements_refined"

const MeasurementUnits = [
    "", "amu", "g/cm3", "g/l", "°C", "K", "MPa",  "kJ/mol", "J/(kg K)", "W/(m K)", "1/K", "m³/mol", "GPa", "m/s",
    "S/m", "Ω m", "m³/kg", "%", "pm", "b", "m²/kg"
] as const
export type MeasurementUnits = typeof MeasurementUnits[number] | Phase | GasAtomicMultiplicities | Series | Color | ElectricalType |
    MagneticType | CrystalStructure | DecayMode | Block


export type UnitsMap =  {[key in  keyof PTDCElementRefined ]:  MeasurementUnits | MeasurementUnits[] | readonly MeasurementUnits[]}
export const UNITS: UnitsMap = {
    symbol: "",
    name: "",
    atomic_number: "",
    atomic_weight: "amu",
    density: ["g/cm3", "g/l"],
    density_liquid: ["g/cm3", "g/l"],
    melting: "°C",
    melting_absolute: "K",
    boiling: "°C",
    boiling_absolute: "K",
    phase: Phase,
    critical_pressure: "MPa",
    critial_temperature: "K",
    heat_fusion: "kJ/mol",
    heat_vaporisation: "kJ/mol",
    specific_heat: "J/(kg K)",
    adiabatic_index: "",
    neel_point: "K",
    thermal_conductivity: "W/(m K)",
    thermal_expansion: "1/K",
    molar_volume: "m³/mol",
    hardness_brinell: "MPa",
    hardness_mohs: "",
    hardness_vickers: "MPa",
    modulus_bulk: "GPa",
    modulus_shear: "GPa",
    modulus_young: "GPa",
    ratio_poisson: "",
    refractive_index: "",
    speed_sound: "m/s",
    valence: "",
    electronegativity: "",
    electroaffinity: "kJ/mol",
    ionization_energy: "kJ/mol",
    dot_hazard_class: "",
    dot_number: "",
    rtecs_number: "",
    nfpa_label: "",
    name_alternative: "",
    name_allotropes: "",
    block: Block,
    group: "",
    period: "",
    series: Series,
    electron_configuration: "",
    color: Color,
    discovery: "",
    gas_phase: GasAtomicMultiplicities,
    cas_number: "",
    cid_number: "",
    electrical_type: ElectricalType,
    electrical_conductivity: "S/m",
    resistivity: "Ω m",
    superconducting_point: "K",
    magnetic_type: MagneticType,
    curie_point: "K",
    magnetic_susceptibility_mass: "m³/kg",
    magnetic_susceptibility_molar: "m³/mol",
    magnetic_susceptibility_volume: "m³/mol",
    abundance_universe: "%",
    abundance_sun: "%",
    abundance_meteorite: "%",
    abundance_earth_crust: "%",
    abundance_ocean: "%",
    abundance_human: "%",
    radius_atomic: "pm",
    radius_covalent: "pm",
    radius_van_der_waals: "pm",
    crystal_structure: CrystalStructure,
    lattice_angles: "",
    lattice_constants: "pm",
    space_group_name: "",
    space_group_number: "",
    half_life: "",
    lifetime: "",
    decay_mode: DecayMode,
    quantum_number: "",
    neutron_cross_section: "b",
    neutron_mass_absorbtion: "m²/kg",
    isotopes_known: "",
    isotopes_stable: "",
    isotopes_abundance: "%"
}
